version: "3.8"

services:
  expenspend-api:
    env_file:
      - .env
    depends_on:
      - app-db
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__AppDbContext=User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Server=app_db;Port=5432;Database=${POSTGRES_DB}; Pooling=true;
      - ASPNETCORE_URLS=http://+:8080

  app-db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
volumes:
  postgres_data:
